name: Test and Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install  

      - name: Run tests
        run: npm test  

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # This ensures the merge only happens if the tests pass

    steps:
      - name: Merge pull request
        uses: peter-evans/merge-pull-request@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  alert:
    runs-on: ubuntu-latest
    needs: test
    if: failure()  # This step runs only if tests fail

    steps:
      - name: Send alert
        run: |
          echo "Tests failed. Please address the errors before merging."
          
